### ISSUE TITLE
我的鑽石鎬消失了

### ISSUE THREAD

**Issue by DannyKao93** [KasukanoOffical/MiyaServer#2]
https://imgur.com/a/oXCj0gj 使用這個鐵砧改名我的鑽石鎬之後 等級消耗了但是鎬直接消失了 
https://www.youtube.com/watch?v=xjPzYI_GnEI 我又拿另一把試了一次 結果相同
https://imgur.com/a/ejwZ7iW 這是我原本的鑽石鎬 不過我之後加到了experienced 4

**Comment by DannyKao93** [comment]
鑽石鎬可以補嗎QQ

**Comment by tutuw002** [comment]
Bug fixed, your pickaxe is now in your inventory.
