### ISSUE TITLE
Power附魔等級問題

### ISSUE THREAD

**Issue by DannyKao93** [KasukanoOffical/MiyaServer#3]
https://www.youtube.com/watch?v=n-b26xk6tZU 這是20等Power的威力 而上限是200等
三等就有親民的5x5 建議限制最高三等就好XD 不然有人真的弄很高等掉落物太多伺服器可能會爆

**Comment by DannyKao93** [comment]
另外希望能幫我把我的鎬power降低到3 不知道怎麼自己降QQ 20挖起來太卡電腦快炸了

**Comment by DannyKao93** [comment]
剛剛自己重新造了一把lvl3的了

**Comment by tutuw002** [comment]
The Power enchantment level limit will be capped at 4 after the update tonight.
