### ISSUE TITLE
地獄的生怪率

### ISSUE THREAD

**Issue by DannyKao93** [KasukanoOffical/MiyaServer#5]
https://imgur.com/a/VSJ1bys
周圍都有做生怪壓制 雷達我開是128x128x256的範圍 也就是水平最大生怪範圍x最高高度 圖中只有一隻豬人似乎是生在岩漿底下 但是生怪率似乎不怎麼高 我的掛機點是低於最低層的生怪點20格的高度 有超過16格怪物生成距離 第二個掛機點是低於最低層40格 依然不怎麼生怪@@
或是有時候生個兩三隻凋零就很少繼續生 請問能不能提高地獄的生怪率之類的XD 照理來說周圍沒怪物的情況應該會生不少凋零下來

**Comment by tutuw002** [comment]
Spawn rate is not modified in this server.
