### ISSUE TITLE
魚類的生成

### ISSUE THREAD

**Issue by DannyKao93** [KasukanoOffical/MiyaServer#7]
想要找到熱帶魚海豚或海龜常常要在同一個地點等待好幾個遊戲天 才會有少少幾隻出現 周圍的生怪都正常 但是似乎魚類的生成特別少

**Comment by DannyKao93** [comment]
不過很可能是因為我房子在世界邊界附近 重生點附近的比較正常

**Comment by tutuw002** [comment]
Again, mob spawning is not modified in this server
